### ISSUE TITLE
F.K.

### ISSUE THREAD

**Issue by Keunmo** [Keunmo/Workshop-sample-2021#1]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: page.chungjungsoo.to_dosample, PID: 2766
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at page.chungjungsoo.to_dosample.MainActivity$onCreate$1.onClick(MainActivity.kt:134)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Keunmo** [comment]
@Taewan-P help me

**Comment by Taewan-P** [comment]
@Keunmo I need to see your code in MainActivity. Can't tell what's wrong with only error logs.

**Comment by Keunmo** [comment]
@Taewan-P see my commit "fuck kotlin"

**Comment by Taewan-P** [comment]
@Keunmo I think this is because you are trying to pop a dialog with a function that you made. The DatePickerDialog might not find which context to pop, resulting null.

Try popping the DatePickerDialog without using your function.

**Comment by Taewan-P** [comment]
@Keunmo Oh I found the reason

**Comment by Keunmo** [comment]
@Taewan-P 
![image](https://user-images.githubusercontent.com/11805551/105833182-303b5180-600c-11eb-8a03-f447ea624f3b.png)
same error..

**Comment by Taewan-P** [comment]
Main Activity cannot find the element setDateBtn that's why.
 Try using findViewbyId and cast this into element

**Comment by Taewan-P** [comment]
I see you already used findViewbyId and used variable setDate

You have to use setDate.setonClickListener instead.

**Comment by Keunmo** [comment]
@Taewan-P I love U. Thx
